// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABY-CjWfXcuhtqhZR2b_uU_jSfeIOdiHc',
    appId: '1:616350285852:web:fd8448506502553bf29fd9',
    messagingSenderId: '616350285852',
    projectId: 'lostandfoundtracker-b0a93',
    authDomain: 'lostandfoundtracker-b0a93.firebaseapp.com',
    storageBucket: 'lostandfoundtracker-b0a93.firebasestorage.app',
    measurementId: 'G-EWK3CLTG00',
    databaseURL: 'https://lostandfoundtracker-b0a93-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXoltZLfO7eVExnDkzU3YIZYywt8xzPmw',
    appId: '1:616350285852:android:0aad44a639a10dd9f29fd9',
    messagingSenderId: '616350285852',
    projectId: 'lostandfoundtracker-b0a93',
    storageBucket: 'lostandfoundtracker-b0a93.firebasestorage.app',
    databaseURL: 'https://lostandfoundtracker-b0a93-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPUZ6qkNFDJNvoihMAt4KrZzhQEhfHm7c',
    appId: '1:616350285852:ios:fd6358a85fc68c96f29fd9',
    messagingSenderId: '616350285852',
    projectId: 'lostandfoundtracker-b0a93',
    storageBucket: 'lostandfoundtracker-b0a93.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPUZ6qkNFDJNvoihMAt4KrZzhQEhfHm7c',
    appId: '1:616350285852:ios:fd6358a85fc68c96f29fd9',
    messagingSenderId: '616350285852',
    projectId: 'lostandfoundtracker-b0a93',
    storageBucket: 'lostandfoundtracker-b0a93.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABY-CjWfXcuhtqhZR2b_uU_jSfeIOdiHc',
    appId: '1:616350285852:web:ac594fe0ac43eac0f29fd9',
    messagingSenderId: '616350285852',
    projectId: 'lostandfoundtracker-b0a93',
    authDomain: 'lostandfoundtracker-b0a93.firebaseapp.com',
    storageBucket: 'lostandfoundtracker-b0a93.firebasestorage.app',
    measurementId: 'G-LC9L5ZRZQN',
  );
}
